[misc]
# remote_topgrades = [ "minibox" ]
# ignore_failures = [ "remotes", "git_repos" ]
disable = ["pip3", "jetbrains_toolbox"]
pre_sudo = true

[pre_commands]

[post_commands]

# Custom commands
[commands]
"Set it up" = "~/dotfiles/setup.sh"

[git]
repos = [
    "~/dotfiles",
    "~/src/clone/*"
]
arguments = "--rebase --autostash"
