[misc]
remote_topgrades = [ "minibox" ]
ignore_failures = [ "remotes" ]

[pre_commands]

[post_commands]

# Custom commands
[commands]
"Stow it" = "~/dotfiles/stow.sh"

[git]
repos = [
    "~/dotfiles"
]
